;; Generate source code files for GNU Emacs from source files.
;; This file is derived from GNU Emacs "lib-src/make-docfile.c".

;; Copyright (C) 1985-1986, 1992-1994, 1997, 1999-2024 Free Software
;; Foundation, Inc.
;;
;; This file is part of GNU Emacs.
;;
;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or (at
;; your option) any later version.
;;
;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.  */


;; The arguments given to this program are all the C files
;; of GNU Emacs.  .c files are allowed.
;; A .o file can also be specified; the .c file it was made from is used.
;; This helps the makefile pass the correct list of files.
;; Option -d DIR means change to DIR before looking for files.

;; The results, which go to standard output or to a file
;; specified with -a or -o (-a to append, -o to start from nothing),
;; are entries containing function or variable names and their documentation.
;; Each entry starts with a ^_ character.
;; Then comes F for a function or V for a variable.
;; Then comes the function or variable name, terminated with a newline.
;; Then comes the documentation for that function or variable.

(use-modules (srfi srfi-9))
(use-modules (ice-9 match)
             (ice-9 format)
             (ice-9 string-fun)
             (ice-9 textual-ports))

(define-syntax LLL
  (syntax-rules ()
    ((_ fmt . args)
     (apply format (list (current-error-port) fmt . args)))))

(define-syntax decf
  (syntax-rules ()
    ((_ var)
     (set! var (1- var)))))
(define-syntax incf
  (syntax-rules ()
    ((_ var)
     (set! var (1+ var)))))

;; ------------------------------------------------
;; similar to (ice-9 streams)

(define %charstack #f)

(define (getc s)
  (if (null? %charstack)
      (get-char s)
      (let ((c (car %charstack)))
        (set! %charstack (cdr %charstack))
        c)))

(define (ungetc c s)
  (set! %charstack (cons c %charstack)))

(define (make-fstream filename)
  (set! %charstack '())
  (open-input-file filename))

(define (fstream-eof? s)
  (eof-object? (lookahead-char s)))


(define (fstream-read-integer-acc s acc)
  (if (eof-object? s)
    acc
    (let ((c (getc s)))
      (cond
       ((char-numeric? c)
        (let ((n (- (char->integer c) 48)))
          (fstream-read-integer-acc s
                                    (if acc
                                        (+ (* acc 10) n)
                                        n))))
       (else
        (ungetc c s)
        acc)))))

(define (fstream-read-integer s)
  (fstream-read-integer-acc s #f))

(define (c-isspace c)
  (memq c
        (list #\Space
              #\Tab
              #\Newline
              ; v
              ; f
              #\Return)))

(define (c-isalpha c)
  (char-alphabetic? c))

(define (c-isalnum c)
  (or (char-alphabetic? c)
      (char-numeric? c)))

(define (c-toupper c)
  (char-upcase c))

(define (putchar c)
  (put-char (current-output-port) c))

(define (puts str)
  (display str)
  (newline))

(define (fputs str s)
  (display str (current-output-port)))

(define stdout 'stdout) ; dummy
(define %input-buffer #f)

;; ------------------------------------------------

;; True if this invocation is generating globals.h.
(define %generate-globals #f)

(define DEFUN_noreturn 1)
(define DEFUN_const 2)
(define DEFUN_noinline 4)
;; Print error message.  Args are like vprintf.

(define (verror m args)
  (apply format (append (list (current-error-port) m) args))
  (format (current-error-port) "~%"))

;; Print error message.  Args are like printf.

(define (print-error m . args)
  (verror m args))

;; Print error message and exit.  Args are like printf.

(define (fatal m . args)
  (verror m args)
  (exit 1))

;; Add a source file name boundary marker in the output file.
(define (put-filename filename)
  (let ((len (string-length filename))
        (new-filename filename))
    (do ((i 0 (1+ i)))
        ((>= i len))
      (if (file-name-separator? (string-ref filename i))
          (set! new-filename (substring filename i))))
    (format #t "~cS~a~%" (integer->char 31) filename)))

;; Read file FILENAME and output its doc strings to stdout.
;; Return true if file is found, false otherwise.  */

(define (scan-file filename)
  (when (not %generate-globals)
    (put-filename filename))
  (scan-c-file filename "r"))

(define (start-globals)
  (format #t "/* This file was auto-generated by make-docfile.  */~%")
  (format #t "/* DO NOT EDIT.  */~%")
  (format #t "struct emacs_globals {~%"))

;; Some state during the execution of `read_c_string_or_comment'.
(define-record-type <rcsoc>
  (make-rcsoc)
  rcsoc?
  ;; A count of spaces and newlines that have been read, but not output.
  (pending-spaces rcsoc-pending-spaces set-rcsoc-pending-spaces)
  (pending-newlines rcsoc-pending-newlines set-rcsoc-pending-newlines)

  ;; Where we're reading from.
  (in-file rcsoc-in-file  set-rcsoc-in-file)

  ;; If non-zero, a buffer into which to copy characters.
  (buf-ptr rcsoc-buf-ptr set-rcsoc-buf-ptr)

  ;; If non-zero, a file into which to copy characters.
  (out-file rcsoc-out-file set-rcsoc-out-file)

  ;; A keyword we look for at the beginning of lines.  If found, it is
  ;; not copied, and SAW_KEYWORD is set to true.
  (keyword rcsoc-keyword set-rcsoc-keyword)
  ;; The current point we've reached in an occurrence of KEYWORD in
  ;; the input stream.
  (cur-keyword-ptr rcsoc-cur-keyword-ptr set-rcsoc-cur-keyword-ptr)
  ;; Set to true if we saw an occurrence of KEYWORD.
  (saw-keyword rcsoc-saw-keyword set-rcsoc-saw-keyword))

(define (dec-rcsoc-pending-spaces r a)
  (set-rcsoc-pending-spaces r (- (rcsoc-pending-spaces r) a)))

(define (inc-rcsoc-pending-spaces r a)
  (set-rcsoc-pending-spaces r (+ (rcsoc-pending-spaces r) a)))

(define (dec-rcsoc-pending-newlines r a)
  (set-rcsoc-pending-newlines r (- (rcsoc-pending-newlines r) a)))

(define (inc-rcsoc-pending-newlines r a)
  (set-rcsoc-pending-newlines r (+ (rcsoc-pending-newlines r) a)))

(define (rcsoc-buf-ptr-put state c)
  (let* ((pair (rcsoc-buf-ptr state))
         (str (car pair))
         (idx (cdr pair)))
    (if (>= idx (string-length str))
        (set! str (string-concatenate (list str (format #f "~c" c))))
        (string-set! str idx c))
    (set-car! pair str)
    (set-cdr! pair (1+ idx))))

(define (charptr-put pair p c)
  (let* ((str (car pair)))
    (if (>= p (string-length str))
        (set! str (string-concatenate (list str (format #f "~c" c))))
        (string-set! str p c))
    (set-car! pair str)))

;(define (ptr-deref pair)
;  (match pair
;    ((str . idx)
;     (if idx
;         (string-ref str idx)
;         (error "cant dereference ptr, no index")))))

;; Output CH to the file or buffer in STATE.  Any pending newlines or
;; spaces are output first.  */

(define (rcsoc-put-char ch state)
  (let ((out-ch #f)
        (done #f))
    (while (not done)
      (cond
        ((> (rcsoc-pending-newlines state) 0)
         (dec-rcsoc-pending-newlines state 1)
         (set! out-ch #\Newline))
        ((> (rcsoc-pending-spaces state) 0)
         (dec-rcsoc-pending-spaces state 1)
         (set! out-ch #\Space))
        (else
         (set! out-ch ch)))
      (if (rcsoc-out-file state)
          (putchar out-ch))
      (if (rcsoc-buf-ptr state)
          (rcsoc-buf-ptr-put state out-ch))
      (if (char=? out-ch ch) (set! done #t)))))

;; If in the middle of scanning a keyword, continue scanning with
;; character CH, otherwise output CH to the file or buffer in STATE.
;; Any pending newlines or spaces are output first, as well as any
;; previously scanned characters that were thought to be part of a
;; keyword, but were in fact not.  */

(define (scan-keyword-or-put-char ch state)
  (cond
   ((let ((keyword (rcsoc-keyword state))
          (cur-keyword-ptr (rcsoc-cur-keyword-ptr state)))
      (and keyword
           (char=? (string-ref keyword cur-keyword-ptr) ch)
           (or (> cur-keyword-ptr (string-length keyword))
               (> (rcsoc-pending-newlines state) 0))))
    ;; We might be looking at STATE->keyword at some point.
    ;; Keep looking until we know for sure.
    (set-rcsoc-cur-keyword-ptr state
                               (1+ (rcsoc-cur-keyword-ptr state)))
    (when (>= (rcsoc-cur-keyword-ptr state) (string-length (rcsoc-keyword state)))
      ;; Saw the whole keyword.  Set SAW_KEYWORD flag to true.
      (set-rcsoc-saw-keyword state #t)

      ;; Reset the scanning pointer.
      (set-rcsoc-cur-keyword-ptr state 0)

      ;; Canonicalize whitespace preceding a usage string.
      (set-rcsoc-pending-newlines state 2)
      (set-rcsoc-pending-spaces state 0)

      ;; Skip any spaces and newlines between the keyword and the
      ;; usage string.
      (let ((done #f)
            (c #f))
        (while (not done)
          (set! c (getc (rcsoc-in-file state)))
          (if (not (or (char=? c #\Space) (char=? c #\Newline)))
              (set! done #t)))

        ;; Output the open-paren we just read.
        (if (not (char=? c #\())
            (fatal "Missing '(' after keyword"))
        (rcsoc-put-char c state))

      ;; Skip the function name and replace it with `fn'.
      (let ((done #f)
            (c #f))
        (while (not done)
          (set! c (getc (rcsoc-in-file state)))
          (if (eof-object? c)
              (fatal "Unexpected EOF after keyword"))
          (if (or (char=? c #\Space) (char=? c #\)))
              (set! done #t)))

        (rcsoc-put-char #\f state)
        (rcsoc-put-char #\n state)

        ;; Put back the last character.
        (ungetc c (rcsoc-in-file state)))))
   (else
    (when (and (rcsoc-keyword state)
               (> (rcsoc-cur-keyword-ptr state) 0))
      ;; We scanned the beginning of a potential usage
      ;; keyword, but it was a false alarm.  Output the
      ;; part we scanned.
      (do ((p 0 (1+ p)))
          ((>= p (rcsoc-cur-keyword-ptr state)))
        (rcsoc-put-char (string-ref (rcsoc-keyword state) p) state))
      (set-rcsoc-cur-keyword-ptr state 0))
    (rcsoc-put-char ch state))))

;; Skip a C string or C-style comment from INFILE, and return the
;; byte that follows, or EOF.  COMMENT means skip a comment.  If
;; PRINTFLAG is positive, output string contents to stdout.  If it is
;; negative, store contents in buf.  Convert escape sequences \n and
;; \t to newline and tab; discard \ followed by newline.
;; If SAW_USAGE is non-null, then any occurrences of the string "usage:"
;; at the beginning of a line will be removed, and *SAW_USAGE set to
;; true if any were encountered.  */

;----------------------------------------------------------------------
(define (read-c-string-or-comment infile printflag comment saw-usage input-buffer)
  (let ((c #f) (state (make-rcsoc)))
    (set-rcsoc-in-file state infile)
    (set-rcsoc-buf-ptr state (if (< printflag 0) input-buffer #f))
    (set-rcsoc-out-file state (if (> printflag 0) stdout #f))
    (set-rcsoc-pending-spaces state 0)
    (set-rcsoc-pending-newlines state 0)
    (set-rcsoc-keyword state (if saw-usage "usage:" #f))
    (set-rcsoc-cur-keyword-ptr state 0)
    (set-rcsoc-saw-keyword state #f)
    (set! c (getc infile))
    (if comment
      (while (c-isspace c)
        (set! c (getc infile))))

    (while (not (eof-object? c))
      (while (and (not (eof-object? c)) (if comment (not (char=? c #\*)) (not (char=? c #\"))))
        (when (char=? c #\\)
          (set! c (getc infile))
          (case c
            ((#\Newline #\Return)
             (set! c (getc infile))
             (continue))
            ((#\n)
             (set! c #\Newline))
            ((#\t) (set! c #\Tab))))

        (cond
         ((char=? c #\Space)
          (inc-rcsoc-pending-spaces state 1))
         ((char=? c #\Newline)
          (inc-rcsoc-pending-newlines state 1)
          (set-rcsoc-pending-spaces state 0))
         (else
          (set! %input-buffer input-buffer)
          (scan-keyword-or-put-char c state)))

        (set! c (getc infile)))

      (if (not (eof-object? c))
        (set! c (getc infile)))

      (cond
       (comment
        (when (char=? c #\/)
          (set! c (getc infile))
          (break))
        (scan-keyword-or-put-char #\* state))
       (else
        (if (not (char=? c #\"))
          (break))
        ;; If we had a "", concatenate the two strings.
        (set! c (getc infile)))))

    (if (< printflag 0)
      (set-car! (rcsoc-buf-ptr state)
                (substring (car (rcsoc-buf-ptr state))
                           0 (cdr (rcsoc-buf-ptr state)))))

    (cons c (rcsoc-saw-keyword state))))


;; Write to stdout the argument names of function FUNC, whose text is in BUF.
;; MINARGS and MAXARGS are the minimum and maximum number of arguments.

(define (write-c-args func buf minargs maxargs)
  (let ((in-ident #f)
        (ident-start #f)
        (ident-length 0)
        (bufi 0))
    (fputs "(fn" stdout)

    (if (char=? #\( (string-ref buf 0))
      (incf bufi))

    (do ((p bufi (1+ p)))
        ((>= p (string-length buf)))
      (catch 'continue
        (lambda ()
      (let ((continue (lambda () (throw 'continue)))
            (c (string-ref buf p)))
        ;; Notice when a new identifier starts.
        (when (not (eq? (or (c-isalnum c) (char=? c #\_)) in-ident))
          (cond
           ((not in-ident)
            (set! in-ident #t)
            (set! ident-start p))
           (else
            (set! in-ident #f)
            (set! ident-length (- p ident-start)))))

        ;; Found the end of an argument, write out the last seen identifier.
        (when (or (char=? c #\,) (char=? c #\)))
          (when (= 0 ident-length)
            (print-error "empty arg list for '~s' should be (void), not ()" func)
            (continue))
          (if (string=? "void" (substring buf ident-start (+ ident-start ident-length)))
            (continue))

          (putchar #\Space)

          (if (and (= 0 minargs) (> maxargs 0))
            (fputs "&optional " stdout))

          (decf minargs)
          (decf maxargs)

          ;; In C code, `default' is a reserved word, so we spell it
          ;; `defalt'; demangle that here.
          (cond
           ((and (= 6 ident-length) (string=? "defalt" (substring buf ident-start (+ ident-start 6))))
            (fputs "DEFAULT" stdout))
           (else
            (while (let ((il ident-length))
                     (decf ident-length)
                     (> il 0))
              (set! c (c-toupper (string-ref buf ident-start)))
              (incf ident-start)
              (if (char=? c #\_)
                ;; Print underscore as hyphen.
                (set! c #\-))
              (putchar c)))))))
        (lambda (kind . args)
          #f)))
    (putchar #\))))

;; The types of globals.  These are sorted roughly in decreasing alignment
;; order to avoid allocation gaps, except that symbols and functions
;; are last.
(define %global-type
 '((INVALID . 0)
   (LISP_OBJECT . 1)
   (EMACS_INTEGER . 2)
   (BOOLEAN . 3)
   (SYMBOL . 4)
   (FUNCTION . 5)))

;; A single global.
(define-record-type <global>
  (make-global)
  global?
  (type global-type set-global-type) ; enum global_type
  (name global-name set-global-name) ;  char *
  (flags global-flags set-global-flags) ; int
  ; union v:
    (value global-value set-global-value) ; int
    (svalue global-svalue set-global-svalue)) ;    char const


;; Bit values for FLAGS field from the above.  Applied for DEFUNs only.
(define %defun-flags
 '(
  DEFUN_noreturn ; 1
  DEFUN_const ; 2
  DEFUN_noinline ; 4
  ))

;; All the variable names we saw while scanning C sources in `-g'
;; mode.
(define num-globals 0)
(define num-globals-allocated 0)
(define %globals '()) ; list of <global>

(define (add-global type name value svalue)
  ;; Ignore the one non-symbol that can occur.
  (cond
   ((not (string= name "..."))
    (incf num-globals)

    (let* ((namesize (1+ (string-length name)))
           (buf (vector (+ namesize (if svalue (1+ (string-length svalue)) 0))))
           (g (make-global)))
      (set-global-type g type)
      (set-global-name g (substring name 0))
      (if svalue
        (set-global-svalue g (substring svalue 0))
        (set-global-value g value))
      (set-global-flags g 0)
      (set! %globals (cons g %globals))
      ; return globals + num_globals - 1
      g))
   (else #f)))

(define (type->num t)
  (cdr (assoc t %global-type)))

(define (strcmp-c-style str1 str2)
  (let loop ((i 0))
    (cond
      ;; If we reach the end of both strings, they are equal
      ((and (= i (string-length str1)) (= i (string-length str2))) 0)
      ;; If we reach the end of str1 but not str2, str1 is smaller
      ((= i (string-length str1)) -1)
      ;; If we reach the end of str2 but not str1, str1 is larger
      ((= i (string-length str2)) 1)
      ;; Compare characters at position i
      ((char<? (string-ref str1 i) (string-ref str2 i)) -1)
      ((char>? (string-ref str1 i) (string-ref str2 i)) 1)
      ;; Characters are equal, continue to the next character
      (else (loop (+ i 1))))))

(define (compare-globals a b)
  (cond
   ((not (eq? (global-type a) (global-type b)))
    (> (type->num (global-type b)) (type->num (global-type a))))
   ;; Consider "nil" to be the least, so that iQnil is zero.  That
   ;; way, Qnil's internal representation is zero, which is a bit faster.
   ;; Similarly, consider "t" to be the second-least, and so forth.  */
   ((eq? (global-type a) 'SYMBOL)
     ;; Common symbols in decreasing popularity order.
    (let ((syma #f) (symb #f) (n 0))
      (for-each (lambda (sym)
                  (set! n (1+ n))
                  (if (and (char=? #\Q (string-ref (global-name a) 0))
                           (string=? (substring (global-name a) 1) sym))
                      (set! syma n))
                  (if (and (char=? #\Q (string-ref (global-name b) 0))
                           (string=? (substring (global-name b) 1) sym))
                      (set! symb n)))
                '("nil" "t" "unbound" "error" "lambda"))
      (if (or syma symb)
          (< (or syma 6) (or symb 6))
          (string<? (global-name a) (global-name b)))))
   (else
    (let ((s1 (global-name a)) (s2 (global-name b)))
      ;(string<? s1 s2)
      (< (strcmp-c-style s1 s2) 0)))))

(define (close-emacs-globals num-symbols)
  (for-each
   (lambda (str)
     (display str)
     (newline))
   `("};"
     "extern struct emacs_globals globals;"
     ""
     ,(format #f "extern Lisp_Object lispsym[~a];" num-symbols)
     "#ifdef DEFINE_SYMBOLS"
     ,(format #f "Lisp_Object lispsym[~a];" num-symbols)
     "#endif")))

(define (write-globals)
  (let ((i #f) (j #f)
        (seen-defun #f)
        (symnum 1)
        (num-symbols 1)
        (takes '()))
    (set! %globals (sort %globals compare-globals))

    (do ((j 0) (i 0 (1+ i)))
        ((>= i (length %globals)))
      (let ((g (list-ref %globals i)))
        ; skip duplicates
        (while (and (< (1+ i) num-globals)
                    (let ((h (list-ref %globals (1+ i))))
                      (string=? (global-name g) (global-name h))))
          (let ((h (list-ref %globals (1+ i))))
            (if (and (eq? (global-type g) 'FUNCTION)
                     (not (= (global-value g) (global-value h))))
                (print-error "function '~a' defined twice with differing signatures"
                             (global-name g)))
            (set! i (1+ i))
            (set! j i)))
        (set! g (list-ref %globals i))
        (set! num-symbols (+ num-symbols
                             (if (eq? (global-type g) 'SYMBOL) 1 0)))
        (set! takes (cons g takes))))
    (set! num-globals (length takes))
    (set! %globals (reverse takes))

    (do ((i 0 (1+ i)))
        ((>= i (length %globals)))
      (let ((type #f)
            (g (list-ref %globals i)))
        (case (global-type g)
          ((EMACS_INTEGER)
           (set! type "intmax_t"))
          ((BOOLEAN)
           (set! type "bool"))
          ((LISP_OBJECT)
           (set! type "Lisp_Object"))
          ((SYMBOL FUNCTION)
           (when (not seen-defun)
             (close-emacs-globals num-symbols)
             (putchar #\Newline)
             (set! seen-defun #t)))
          (else
           (fatal "not a recognized DEFVAR_")))
        (cond
         (type
          (format #t "  ~a f_~a;~%" type (global-name g))
          (format #t "#define ~a globals.f_~a~%"
                  (global-name g) (global-name g)))
         ((eq? (global-type g) 'SYMBOL)
          (format #t "#define i~a ~a~%" (global-name g) symnum)
          (format #t "#define ~a builtin_lisp_symbol (i~a)~%"
                  (global-name g) (global-name g))
          (set! symnum (1+ symnum)))
         (else
          (if (not (= 0 (logand (global-flags g) DEFUN_noreturn)))
              (fputs "_Noreturn " stdout))
          (if (not (= 0 (logand (global-flags g) DEFUN_noinline)))
              (fputs "NO_INLINE " stdout))

          (format #t "EXFUN (~a, " (global-name g))
          (cond
           ((= -1 (global-value g))
            (fputs "MANY" stdout))
           ((= -2 (global-value g))
            (fputs "UNEVALLED" stdout))
           (else
            (format #t "~a" (global-value g))))
           (putchar #\))

           (if (not (= 0 (logand (global-flags g) DEFUN_noreturn)))
               (fputs " ATTRIBUTE_COLD" stdout))
           (if (not (= 0 (logand (global-flags g) DEFUN_const)))
               (fputs " ATTRIBUTE_CONST" stdout))

           (puts ";")))))

    (if (not seen-defun)
        (close-emacs-globals num-symbols))

    (puts "#define iQnil 0")
    (puts "DEFINE_LISP_SYMBOL (Qnil)")
    (puts "#ifdef DEFINE_SYMBOLS")
    (puts "static char const *const defsym_name[] = {")
    (format #t "~t\"nil\",~%")
    (do ((i 0 (1+ i))) ((>= i num-globals))
      (let ((g (list-ref %globals i)))
        (if (eq? (global-type g) 'SYMBOL)
            (format #t "~t\"~a\",~%"
                    (global-svalue g)
                    ;(string-replace-substring (substring (global-svalue g) 1)
                    ;                "_" "-")
                    ))))
    (puts "};")
    (puts "#endif")

    (puts "#define Qnil builtin_lisp_symbol (0)")
    (puts "#if DEFINE_NON_NIL_Q_SYMBOL_MACROS")
    (set! num-symbols 0)
    (do ((i 0 (1+ i))) ((>= i num-globals))
      (let ((g (list-ref %globals i)))
        ; dont print first symbol, already printed above
        (when (eq? (global-type g) 'SYMBOL)
          (if (> num-symbols 0)
              (format #t "# define ~a builtin_lisp_symbol (~a)~%"
                      (global-name g) num-symbols))
          (set! num-symbols (1+ num-symbols)))))
    (puts "#endif")))

;; Read through a c file.  If a .o file is named,
;; the corresponding .c or .m file is read instead.
;; Looks for DEFUN constructs such as are defined in ../src/lisp.h.
;; Accepts any word starting DEF... so it finds DEFSIMPLE and DEFPRED.  */

(define (scan-c-file filename mode)
  (let* ((flen (string-length filename))
         (infile #f)
         (extension (string-ref filename (1- flen)))
         (rfile filename))
    (if (char=? extension #\o)
        (set! rfile (string-concatenate (list (substring rfile 0 (1- flen)) "c"))))

    ;; Try .m.
    (if (not (file-exists? rfile))
        (set! rfile (string-concatenate (list (substring rfile 0 (1- flen)) "m"))))

    (if (not (file-exists? rfile))
        (error "missing file: ~s" filename))
    (scan-c-stream (make-fstream rfile))))

;; Return 1 if next input from INFILE is equal to P, -1 if EOF,
;; 0 if input doesn't match.

(define (stream-match s p i)
  (let ((c (getc s)))
    (cond
     ((>= i (string-length p)) 1)
     ((eof-object? c) -1)
     ((not (char=? c (string-ref p i))) 0)
     (else
      (stream-match s p (1+ i))))))

(define (scan-c-stream infile)
 (catch 'eof
  (lambda ()
   (let ((commas #f) (minargs #f) (maxargs #f)
         (c #\Newline)
         (input-buffer (cons "" 0)))
    (while (not (fstream-eof? infile))
      (let ((doc_keyword #f)
            (defunflag #f)
            (defvarperbufferflag #f)
            (defvarflag #f)
            (type 'INVALID)
            (name #f))
        (set! input-buffer (cons "" 0)) ; FIX: bad state for input-buffer
        (when (and (not (char=? #\Newline c)) (not (char=? #\Return c)))
          (set! c (getc infile))
          (continue))
        (set! c (getc infile))
        (cond
         ((char=? c #\Space)
          (while (char=? c #\Space)
            (set! c (getc infile)))
          (if (not (char=? c #\D)) (continue))
          (set! c (getc infile))
          (if (not (char=? c #\E)) (continue))
          (set! c (getc infile))
          (if (not (char=? c #\F)) (continue))
          (set! c (getc infile))
          (cond
           ((char=? c #\S)
            (set! c (getc infile))
            (if (not (char=? c #\Y)) (continue))
            (set! c (getc infile))
            (if (not (char=? c #\M)) (continue))
            (set! c (getc infile))
            (if (and (not (char=? c #\Space)) (not (char=? c #\Tab)) (not (char=? c #\()))
                (continue))
            (set! type 'SYMBOL))
           ((char=? c #\V)
            (set! c (getc infile))
            (if (not (char=? c #\A)) (continue))
            (set! c (getc infile))
            (if (not (char=? c #\R)) (continue))
            (set! c (getc infile))
            (if (not (char=? c #\_)) (continue))

            (set! defvarflag #t)

            (set! c (getc infile))
            (set! defvarperbufferflag (char=? c #\P))
            (if %generate-globals
              (cond
               ((char=? c #\I)
                (set! type 'EMACS_INTEGER))
               ((char=? c #\L)
                (set! type 'LISP_OBJECT))
               ((char=? c #\B)
                (set! type 'BOOLEAN))))

            (set! c (getc infile))
            ;; We need to distinguish between DEFVAR_BOOL and
            ;; DEFVAR_BUFFER_DEFAULTS.
            (if (and %generate-globals (eq? type 'BOOLEAN) (not (char=? c #\O)))
              (set! type 'INVALID)))
           (else
            (continue))))
         ((char=? c #\D)
          (set! c (getc infile))
          (if (not (char=? c #\E)) (continue))
          (set! c (getc infile))
          (if (not (char=? c #\F)) (continue))
          (set! c (getc infile))
          (set! defunflag (eqv? c #\U)))
         (else
          (continue)))

        (if (and %generate-globals
                 (or (not defvarflag) defvarperbufferflag (eq? type 'INVALID))
                 (not defunflag)
                 (not (eq? type 'SYMBOL)))
            (continue))

        (while (not (char=? c #\())
          (if (eof-object? c)
              (throw 'eof))
          (set! c (getc infile)))

        (when (not (eq? type 'SYMBOL))
          ;; Lisp variable or function name.
          (set! c (getc infile))
          (if (not (char=? c #\")) (continue))
          (set! c (car (read-c-string-or-comment infile -1 #f #f input-buffer)))
          )

      (when %generate-globals
        (let ((i 0)
              (svalue #f))
          (set! input-buffer (cons "" 0))
          ;; Skip "," and whitespace.
          (while #t
            (set! c (getc infile))
            (if (not (or (char=? c #\,) (c-isspace c)))
                (break)))
          ;; Read in the identifier.
          (while #t
            (if (eof-object? c) (throw 'eof))
            (set-car! input-buffer (format #f "~a~c" (car input-buffer) c))
            (set! i (1+ i))
            (set! c (getc infile))
            (if (or (char=? c #\,) (c-isspace c))
                (break)))

          (set! name (substring (car input-buffer) 0))

          (when (eq? type 'SYMBOL)
            (while #t
              (set! c (getc infile))
              (if (not (c-isspace c))
                  (break)))

            (if (not (char=? c #\"))
              (continue))
            (set! c (car (read-c-string-or-comment infile -1 #f #f input-buffer)))
            (set! svalue (car input-buffer)))

          (when (not defunflag)
            (add-global type name 0 svalue)
            (continue))))

      (if (eq? type 'SYMBOL)
          (continue))

      ;; DEFVAR_LISP ("name", addr, "doc")
      ;; DEFVAR_LISP ("name", addr /\* doc *\/)
      ;; DEFVAR_LISP ("name", addr, doc: /\* doc *\/)

      (cond
       (defunflag
         (set! commas (if %generate-globals 4 5)))
       (defvarperbufferflag
         (set! commas 3))
       (defvarflag
         (set! commas 1))
       (else  ;; For DEFSIMPLE and DEFPRED.
        (set! commas 2)))

      (while (> commas 0)
        (when (and (not (eof-object? c)) (char=? #\, c))
          (decf commas)
          (if (and defunflag (or (= commas 1) (= commas 2)))
            (let ((scanned #f))
              (while #t
                (set! c (getc infile))
                (if (not (c-isspace c))
                    (break)))
              (if (eof-object? c)
                  (throw 'eof))
              (ungetc c infile)
              (cond
               ((= commas 2) ;; Pick up minargs.
                (let ((num (fstream-read-integer infile)))
                  (set! scanned (or scanned num))
                  (if num (set! minargs num))))
               (else ;; Pick up maxargs.
                (cond
                 ((or (char=? c #\M) (char=? c #\U)) ;; MANY || UNEVALLED
                  (set! scanned 'ok)
                  (set! maxargs (if %generate-globals
                                    (if (char=? c #\M) -1 -2)
                                    -1)))
                 (else
                  (let ((num (fstream-read-integer infile)))
                    (set! scanned (or scanned num))
                    (if num (set! maxargs num)))))))
              '(if (not scanned)
                (throw 'eof)))))

        (if (eof-object? c)
            (throw 'eof))
        (set! c (getc infile)))

      (when %generate-globals
        (let ((g (add-global 'FUNCTION name maxargs #f)))
          (if (not g) (continue))
          ;; The following code tries to recognize function attributes
          ;; specified after the docstring, e.g.:

          ;; DEFUN ("foo", Ffoo, Sfoo, X, Y, Z,
          ;; doc: /\* doc *\/
          ;; attributes: attribute1 attribute2 ...)
          ;;   (Lisp_Object arg...)

          ;; Now only `const', `noinline' and `noreturn' attributes
          ;; are used.

          ;; Advance to the end of docstring.
          (set! c (getc infile))
          (if (eof-object? c)
              (throw 'eof))
          (let ((d (getc infile)))
            (if (eof-object? d)
                (throw 'eof))
            (while #t
              (if (and (char=? c #\*) (char=? d #\/))
                  (break))
              (set! c d)
              (set! d (getc infile))
              (if (eof-object? d)
                  (throw 'eof)))
            ;; Skip spaces, if any.
            (while #t
              (set! c (getc infile))
              (if (eof-object? c)
                  (throw 'eof))
              (if (not (c-isspace c)) (break)))

            ;; Check for 'attributes:' token.
            (if (and (char=? c #\a) (stream-match infile "ttributes:" 0))
              (let ((p 0))
                ;; Collect attributes up to ')'.
                (while #t
                  (set! c (getc infile))
                  (if (eof-object? c)
                    (throw 'eof))
                  (if (char=? c #\))
                      (break))
                  (charptr-put input-buffer p c)
                  (set! p (1+ p)))
                (set-car! input-buffer (substring (car input-buffer) 0 p))
                (if (string-contains (car input-buffer) "noreturn")
                    (set-global-flags g (logior (global-flags g) DEFUN_noreturn)))
                (if (string-contains (car input-buffer) "const")
                    (set-global-flags g (logior (global-flags g) DEFUN_const)))
                ;; Although the noinline attribute is no longer used,
                ;; leave its support in, in case it's needed later.
                (if (string-contains (car input-buffer) "noinline")
                    (set-global-flags g (logior (global-flags g) DEFUN_noinline))))))
          (continue)))

        (while (c-isspace c)
          (set! c (getc infile)))

        (if (char=? c #\")
            (set! c (car (read-c-string-or-comment infile 0 #f #f input-buffer))))

        (while (and (not (eof-object? c)) (not (char=? c #\,)) (not (char=? c #\/)))
          (set! c (getc infile)))
        (when (char=? c #\,)
          (while #t
            (set! c (getc infile))
            (if (not (c-isspace c)) (break)))

            (while (c-isalpha c)
              (set! c (getc infile)))
            (when (char=? c #\:)
              (set! doc_keyword #t)
              (while #t
                (set! c (getc infile))
                (if (not (c-isspace c)) (break)))))

        (when (or (char=? c #\")
                  (and (char=? c #\/)
                       (begin ; peek-char
                         (set! c (getc infile))
                         (ungetc c infile)
                         (char=? c #\*))))
           (let ((comment (not (char=? c #\")))
                 (saw_usage #f))
             (format #t "~c~c~a\n"
                        (integer->char 31)
                        (if defvarflag #\V #\F) (car input-buffer))

             (if comment
               (getc infile))   ;; Skip past `*'.
             (match (read-c-string-or-comment infile 1 comment #t input-buffer)
               ((new-c . new-saw-usage)
                (set! c new-c)
                (set! saw_usage new-saw-usage)))
             (set! input-buffer (cons "" 0)) ; FIX: bad state for input-buffer

             ;; If this is a defun, find the arguments and print them.  If
             ;; this function takes MANY or UNEVALLED args, then the C source
             ;; won't give the names of the arguments, so we shouldn't bother
             ;; trying to find them.

             ;; Various doc-string styles:
             ;;  0: DEFUN (..., "DOC") (args)            [!comment]
             ;;  1: DEFUN (..., /\* DOC *\/ (args))      [comment && !doc_keyword]
             ;;  2: DEFUN (..., doc: /\* DOC *\/) (args) [comment && doc_keyword]

             (cond
              ((and defunflag (not (= maxargs -1)) (not saw_usage))
               (let* ((p '()))
                 (if (or (not comment) doc_keyword)
                     (while (not (char=? c #\)))
                       (if (eof-object? c) (throw 'eof))
                       (set! c (getc infile))))
                 ;; Skip into arguments.
                 (while (not (char=? c #\())
                   (if (eof-object? c) (throw 'eof))
                   (set! c (getc infile)))
                 ;; Copy arguments into ARGBUF.
                 (set! p (cons c p)) ;(set-stream-buf p c) ;(set-stream-idx p (1+ (stream-idx p)))
                 (while #t
                   (set! c (getc infile))
                   (if (eof-object? c) (throw 'eof))
                   (set! p (cons c p))
                   (if (char=? c #\)) (break)))

                 ;; Output them.
                 (fputs (format #f "~%~%") stdout)
                 (write-c-args (car input-buffer) (list->string (reverse p)) minargs maxargs)))
              ((and defunflag (= maxargs -1) (not saw_usage))
               ;; The DOC should provide the usage form.
               (format (current-error-port) "Missing 'usage' for function '~a'.~%"
                       input-buffer)))))))))
  (lambda (kind . args)
    #f)))

;;;; -------------------------------------------------------------------

(define (handle-command-line-args args acc)
  (let ((setarg (lambda (key val)
                  (assq-set! acc key val)))
        (pusharg (lambda (key val)
                   (if (assq key acc)
                       (assq-set! acc key
                                  (cons val
                                        (cdr (assq key acc))))
                       (assq-set! acc key
                                  (list val))))))
    (if (null? args)
        acc
        (let ((arg (car args))
              (more (not (null? (cdr args)))))
          (cond
           ;; handle one-term arguments (eg -g)
           ;; rest arguments are treated as input files
           ((string=? "-g" arg)
            (handle-command-line-args (cdr args)
                                      (setarg #:generate-globals #t)))
           ;; handle two-term arguments (eg -o file)
           ((and more (string=? "-o" arg))
            (handle-command-line-args (cddr args)
                                      (setarg #:out-file (cadr args))))
           ((and more (string=? "-a" arg))
            (handle-command-line-args (cddr args)
                                      (setarg #:append-file (cadr args))))
           ((and more (string=? "-d" arg))
            (handle-command-line-args (cddr args)
                                      (setarg #:directory (cadr args))))
           (else
            (handle-command-line-args (cdr args)
                                      (pusharg #:files arg))))))))

(define (main args)
  ;; handle command-line arguments
  (let ((options (handle-command-line-args (cdr args) '())))
    ;; If first two args are -o FILE, output to FILE.
    (if (assq #:out-file options)
        (let ((file (assq-ref options #:out-file)))
          (when (not (freopen file "w" stdout))
            (print-error "~a" file)
            (exit EXIT_FAILURE))))
    (if (assq #:append-file options)
        (let ((file (assq-ref options #:append-file)))
          (when (not (freopen file "a" stdout))
            (print-error "~a" file)
            (exit EXIT_FAILURE))))
    (if (assq #:directory options)
        (chdir (assq-ref options #:directory)))
    (set! %generate-globals (assq #:generate-globals options))

    ;(set-binary-mode (fileno stdout) O_BINARY)

    (if %generate-globals
        (start-globals))

    (for-each (lambda (file)
                (format (current-error-port) "-- scan-file ~s~%" file)
                (scan-file file))
              (reverse (cdr (assq #:files options))))

    (format (current-error-port) "~%-- number of globals: ~s~%"
            (length %globals))
    (if %generate-globals
        (write-globals))

    (exit EXIT_SUCCESS)))
