;;; macroexp-preload.el --- Generate expanded macroexp -*- lexical-binding: t -*-

;; This helper is used during bootstrap to avoid loading `pcase' before
;; eager macro-expanders are available.  It reads `macroexp.el', selectively
;; expands forms that rely on `pcase', and writes the transformed output into
;; `macroexp-expanded.el'.

(defvar macroexp--pending-eager-loads) ; Silences let-binding before macroexp.

(defconst macroexp-preload--dir
  (file-name-directory (or load-file-name buffer-file-name))
  "Directory where the macroexp sources live.")

(defconst macroexp-preload--source
  (expand-file-name "macroexp.el" macroexp-preload--dir)
  "Absolute path to the canonical macroexp source file.")

(defconst macroexp-preload--output
  (expand-file-name "macroexp-expanded.el" macroexp-preload--dir)
  "Absolute path to the generated macroexp output.")


(defun macroexp-preload--pcase-symbol-p (sym)
  "Return non-nil if SYM appears to designate a pcase macro."
  (and (symbolp sym)
       (let ((name (symbol-name sym)))
         (or (string-prefix-p "pcase" name)
             (string-prefix-p "pcase--" name)))))

(defun macroexp-preload--host-load-path ()
  "Return `load-path' with the macroexp source directory removed."
  (let ((target (expand-file-name macroexp-preload--dir)))
    (delq nil
          (mapcar (lambda (path)
                    (let ((expanded (expand-file-name path)))
                      (unless (file-equal-p expanded target)
                        path)))
                  load-path))))

(defun macroexp-preload--expand-tail (tail)
  "Recursively expand each element of TAIL with `macroexp-preload--expand-form'."
  (cond
   ((null tail) nil)
   ((consp tail)
    (cons (macroexp-preload--expand-form (car tail))
          (macroexp-preload--expand-tail (cdr tail))))
   (t (macroexp-preload--expand-form tail))))

(defun macroexp-preload--expand-form (form)
  "Return FORM with embedded `pcase' constructs expanded."
  (cond
   ((atom form) form)
   ((eq (car form) 'quote) form)
   ((eq (car form) 'function)
    (cons 'function
          (macroexp-preload--expand-tail (cdr form))))
   ((eq (car form) 'lambda)
    (let ((args (cadr form))
          (body (cddr form)))
      (cons 'lambda
            (cons args (macroexp-preload--expand-tail body)))))
   (t
    (let ((expanded form)
          (changed nil)
          (max-depth 10))
      (while (and expanded (consp expanded) (symbolp (car expanded))
                  (macroexp-preload--pcase-symbol-p (car expanded))
                  (> max-depth 0))
        (setq max-depth (1- max-depth))
        (let ((next (macroexpand expanded)))
          (if (eq next expanded)
              (setq expanded nil)
            (setq expanded next changed t))))
      (cond
       ((null expanded)
        ;; Nothing changed; recurse into sub-forms.
        (cons (macroexp-preload--expand-form (car form))
              (macroexp-preload--expand-tail (cdr form))))
       (changed
        ;; A `pcase' form was expanded; recurse on the new expansion.
        (macroexp-preload--expand-form expanded))
       (t
        ;; No `pcase' at the top level; walk sub-forms normally.
        (cons (macroexp-preload--expand-form (car form))
              (macroexp-preload--expand-tail (cdr form)))))))))

(defun macroexp-preload--expand (form)
  "Expand only the `pcase'-powered parts of FORM."
  (let ((lexical-binding t))
    (macroexp-preload--expand-form form)))

(defun macroexp-preload--read-forms (file)
  "Read every Lisp form from FILE and return them as a list."
  (with-temp-buffer
    (insert-file-contents file)
    (goto-char (point-min))
    (let (forms)
      (condition-case nil
          (while t
            (push (read (current-buffer)) forms))
        (end-of-file))
      (nreverse forms))))

(defun macroexp-preload--write-file (file forms)
  "Write FORMS into FILE using `prin1'."
  (let ((print-level nil)
        (print-length nil)
        (print-circle nil))
    (with-temp-file file
      (insert ";;; macroexp-expanded.el --- Generated macroexp -*- lexical-binding: t -*-\n")
      (insert ";;; This file is auto-generated by macroexp-preload.el.\n")
      (insert ";;; Do not edit this file directly.\n\n")
      (dolist (form forms)
        (prin1 form (current-buffer))
        (insert "\n\n")))))

(defun macroexp-preload--ensure-output ()
  "Generate `macroexp-expanded.el' when the source is newer."
  (when (or (not (file-exists-p macroexp-preload--output))
            (file-newer-than-file-p macroexp-preload--source
                                    macroexp-preload--output))
    (let ((forms (macroexp-preload--read-forms macroexp-preload--source)))
      (macroexp-preload--write-file
       macroexp-preload--output
       (mapcar #'macroexp-preload--expand forms)))))

(defun macroexp-preload-load ()
  "Generate and load the expanded macroexp implementation."
  (let ((macroexp--pending-eager-loads '(skip))
        (load-path (macroexp-preload--host-load-path)))
    (require 'macroexp)
    (require 'pcase))
  (macroexp-preload--ensure-output)
  (load macroexp-preload--output nil 'nomessage))

(provide 'macroexp-preload)

;;; macroexp-preload.el ends here
