(load "portable.scm")

(use-modules (ice-9 format)
             (ice-9 match)
             (ice-9 popen)
             (ice-9 textual-ports))


(define %prog #f)
(define %args #f)


(define %gdb-proc #f)

(define (set-prog prog)
  (set! %prog prog))

(define (set-args args)
  (set! %args args))

(define (set-env envs)
  (for-each (lambda (p)
              (format #t "----ENV---- ~s=~s~%" (car p) (cadr p))
              (putenv (format #f "~s=~s" (car p) (cadr p)))
              (setenv (car p) (cadr p)))
            envs))

(define (gdb-mi-hickup proc)
  (let ((input-port proc)
        (lst '()))
    (let loop ((line (get-line input-port)))
      ;(format #t "  hickup: ~a~%" line)
      (cond
       ((string-prefix? "(gdb)" line)
        ;(format #t "  final-hickup~%")
        (reverse lst))
       (else
        (set! lst (cons line lst))
        (loop (get-line input-port)))))))

(define (clean-lines lines fils)
  (map (lambda (line)
         (for-each (lambda (str)
                     (set! line (string-replace-substring line str "")))
                   fils)
         line)
       lines))

(define (gdb-mi-command proc command . args)
  "Send a GDB/MI command to the GDB process and read the response."
  (let* ((output-port proc)
         (input-port proc)
         (silent (member 'silent args))
         (clean (member 'clean args))
         (lst '()))
    (if (not silent)
      (format #t "gdb<<< ~a~%" command))
    ;; Send the command to GDB
    (display command output-port)
    (newline output-port)
    (force-output output-port)

    ;; Read the response from GDB
    (let loop ((line (get-line input-port)))
      ;(format #t "  gdb>>> ~a~%" line)
      (if (string-prefix? "(gdb)" line)
        'done
        (begin
          (if clean
              (for-each (lambda (str)
                          (set! line (string-replace-substring line str "")))
                        %clean-line))
          (set! lst (cons line lst))
          (if (not silent)
            (format #t "~a~%" line))
          ;(display line)
          ;(newline)
          (loop (get-line input-port)))))
    (reverse lst)))

(define (start-gdb-mi)
  "Start GDB with the MI interface."
  ;(let ((proc (open-pipe* OPEN_BOTH "gdb" "--interpreter=mi")))
  ;(let ((proc (open-pipe* OPEN_BOTH "./gdb.sh")))
  ;(let ((proc (open-pipe* OPEN_BOTH "/usr/bin/env")))
  (let ((proc (apply open-pipe* OPEN_BOTH %args)))
    (set! %gdb-proc proc)))

(define (inst-str? line str)
  (string-contains line str))

(define (inst-call? line)
  (inst-str? line "\"call "))

(define (get-rax proc)
  (let ((lines (gdb-mi-command proc "-data-evaluate-expression \"$rax\"" 'silent)))
    ;(format #t "-- rax: ~s~%" lines)
    (for-each (lambda (line)
                (when (= 0 (or (string-contains line "^done,value=\"") -1))
                  (set! line (substring line 13))
                  (set! line (string-trim-right line (lambda (x) (char=? x #\"))))
                  ;(format #t "rax=~s~%" line)
                  (set! line (inexact->exact (string->number line)))
                  (format #t "rax=~x~%" line)))
              lines)))

(define (gdb-cli proc)
  "Continue reading GDB output until process ends."
  (let ((line (get-line proc)))
    (cond
     ((eof-object? line)
      (close-pipe proc))
     (else
      (format #t "~a~%" line)
      (gdb-cli proc)))))

(define (run-gdb)
  (let ((gdb-proc %gdb-proc))
    (gdb-mi-hickup gdb-proc)
    (gdb-mi-command gdb-proc (string-concatenate (list "-file-exec-and-symbols " %prog)))
;   (gdb-mi-command gdb-proc "-exec-arguments -batch --no-site-file --no-site-lisp")
;   (gdb-mi-command gdb-proc "-break-insert defvar_lisp_nopro")
;   (gdb-mi-command gdb-proc "-break-insert defvar_lisp")
;    (gdb-mi-command gdb-proc "-break-insert Fgdb_break")
    (gdb-mi-command gdb-proc "-break-insert init_obarray_once")
;   (gdb-mi-command gdb-proc "-break-insert debug_print")
;   (gdb-mi-command gdb-proc "-break-insert main")
    ; char* lname = lisp-name , fn SCM, sym SCM symbol
    ;(gdb-mi-command gdb-proc "-break-insert -t set_symbol_function")
    ;(gdb-mi-command gdb-proc "-interpreter-exec console \"display/i $pc\"")
    (gdb-mi-command gdb-proc "-exec-run")
    ; this hickup is waiting for the breakpoint
    (gdb-mi-hickup gdb-proc)
    (let ((c #f) (p #f))
      (do ((i 0 (1+ i)))
          ((> i 4000000))
        ;(format #t "-------------------------------------------------------------~%")
        (let* ((lines (gdb-mi-command gdb-proc "-data-disassemble -s $pc -e $pc+8" 'silent))
               (lines (map (lambda (line)
                             (let ((n (string-contains line "asm_insns=[{")))
                               (if n
                                   (let ((line (substring line (+ n 12))))
                                     (substring line 0 (string-contains line "}")))
                                   line)))
                           lines))
               (line (car lines)))
          ;(format #t "~a~%" lines)
          (set! p #t)
          (set! c #f)
          (set! c
                (cond
                 ((inst-call? line)
                  (cond
                   ((inst-str? line "<scm_atomic_ref_scm>") 'next)
                   ((inst-str? line "<pthread_mutex_unlock@plt>") 'next)
                   ((inst-str? line "<pthread_mutex_trylock@plt>") 'next)
                   ((inst-str? line "<copy_weak_entry>") 'next)
                   ((inst-str? line "<GC_call_with_alloc_lock@plt>") 'next)
                   ((inst-str? line "<move_weak_entry>") 'next)
                   ((inst-str? line "<GC_move_disappearing_link@plt>") 'next)
                   ((inst-str? line "<vm_push_sp>") 'next)
                   ((inst-str? line "<_setjmp@plt>") 'next)
                   ((inst-str? line "<hash_to_index>") 'next)
                   ((inst-str? line "<entry_distance>") 'next)
                   ((inst-str? line "<scm_is_pair@plt>") 'next)
                   ((inst-str? line "<memcpy@plt>") 'next)
                   ((inst-str? line "<strcmp@plt>") 'next)
                   ((inst-str? line "<strncmp@plt>") 'next)
                   ((inst-str? line "<strchr@plt>") 'next)
                   ((inst-str? line "<strlen@plt>") 'next)
                   ((inst-str? line "<getenv@plt>") 'next)
                   ((inst-str? line "<do_lookup_x>") 'next)
                   ((inst-str? line "<_dl_fixup>") 'next)
                   ((inst-str? line "<_dl_lookup_symbol_x>") 'next)
                   ((inst-str? line "<_dl_map_object>") 'next)
                   ((inst-str? line "<get_callee_vcode>") 'next)
                   ((inst-str? line "<frame_locals_count>") 'next)
                   ((inst-str? line "<scm_dynwind_begin@plt>") 'next)
                   ((inst-str? line "<scm_dynwind_unwind_handler@plt>") 'next)
                   ((inst-str? line "<scm_inline_gc_malloc_words>") 'next)
                   ((inst-str? line "<scm_i_init_thread_for_guile>") 'next)
                   ((inst-str? line "<libunistring_c_strcasecmp@plt>") 'next)
                   ((inst-str? line "<scm_i_set_boot_program_arguments>") 'next)
                   ((inst-str? line "<locale_arguments_to_string_list>") 'next)
                   ((inst-str? line "<environ_locale_charset>") 'next)
                   ((inst-str? line "<__tls_get_addr@plt>") 'next)
                   ((inst-str? line "<scm_current_error_port@plt>") 'next)
                   ((inst-str? line "<scm_fluid_ref@plt>") 'next)
                   ((inst-str? line "<scm_is_fluid@plt>") 'next)
                   ((inst-str? line "<scm_intern@plt>") 'next)
                   ((inst-str? line "<scm_raw_ihashq>") 'next)
                   ((inst-str? line "<scm_cache_lookup>") 'next)
                   ((inst-str? line "<lookup_interned_symbol>") 'next)
                   ((inst-str? line "<scm_cons@plt>") 'next)
                   ((inst-str? line "<scm_cell@plt>") 'next)
                   ((inst-str? line "<scm_make_smob@plt>") 'next)
                   ((inst-str? line "<scm_new_smob@plt>") 'next)
                   ((inst-str? line "<scm_find_symbol@plt>") 'next)
                   ((inst-str? line "<GC_malloc@plt>") 'next)
                   ((inst-str? line "<__GI_getenv>") 'next)
                   ((inst-str? line "<__GI___memmem>") 'next)
                   ((inst-str? line "<__GI___strdup>") 'next)
                   ((inst-str? line "<malloc@plt>") 'next)
                   ((inst-str? line "<_nl_find_locale>") 'next)
                   ((inst-str? line "<get_callee_vcode>") 'next)
                   ((inst-str? line "<sort_args>") 'next)
                   ((inst-str? line "<rob_from_rich>") 'next)
                   ((inst-str? line "<scm_weak_table_p>") 'next)
                   ((inst-str? line "<scm_double_cell@plt>") 'next)
                   ((inst-str? line "<scm_i_make_symbol>") 'next)
                   ((inst-str? line "<scm_hash_fn_get_handle@plt>") 'next)
                   ((inst-str? line "<do_gc_malloc_atomic>") 'next)
                   ((inst-str? line "<make_fixnum>") 'next)
                   ((inst-str? line "<make_vector>") 'next)
                   ((inst-str? line "<make_string>") 'next)
                   ;((inst-str? line "<>") 'next)
                   ;((inst-str? line "<>") 'next)
                   ))
                 ((inst-str? line "\"vm_regular_engine\",")
                  (set! p #f)
                  #f)
                 ((inst-str? line "\"vm_debug_engine\",")
                  (set! p #f)
                  #f)
                 ((inst-str? line "\"get_callee_vcode\",")
                  (set! p #f)
                  #f)))
          (if p
            (format #t "~a ~a ~s~%" i (if (eq? c 'next) 'next 'step) lines))
          (cond
           ((eq? c 'next)
            (gdb-mi-command gdb-proc "-exec-next-instruction" 'silent))
           ;((number? c)
           ; (gdb-mi-command gdb-proc (format #f "-exec-next-instruction ~a" c) 'silent))
           (else
            (gdb-mi-command gdb-proc "-exec-step-instruction" 'silent)))
          (gdb-mi-hickup gdb-proc)
          (if p
            (get-rax gdb-proc)))))))

;; parse cli, setup config, run-gdb
(let* ((get-longarg (lambda (str what)
                      (let ((n (string-contains str what)))
                        (if n
                          (let ((str (substring str (string-length what))))
                            (if (string-index str #\=)
                                (substring str 1)
                                str))
                          #f))))
       (script #f))
  (for-each (lambda (arg)
              (cond
               ((get-longarg arg "--help") =>
                (lambda (arg)
                  (format #t "Help!~%")))
               ((get-longarg arg "--script") =>
                (lambda (arg)
                  (set! script arg)))))
            (command-line))
  (format #t "cli: ~s~%" (command-line))
  (if script
    (load script)))
