
(for-each (lambda (tri)
            (match tri
              ((x y e)
               (deftestf 'ceiling (e)
                 (el-expr `(let ((x ,x)
                                 (y ,y))
                             (print (ceiling x y))))))))
          `((10 3 4)
            (10 -3 -3)
            (-10 3 -3)
            (-10 -3 4)
            (9.0001 3 4)
            (-11.9999 3 -3)
            (10 -3.3334 -2)))

(for-each (lambda (tri)
            (match tri
              ((x y e)
               (deftestf 'floor (e)
                 (el-expr `(let ((x ,x)
                                 (y ,y))
                             (print (floor x y))))))))
          `((10 3 3)
            (10 -3 -4)
            (-10 3 -4)
            (-10 -3 3)
            (9.0001 3 3)
            (-11.9999 3 -4)
            (10 -3.3334 -3)))

(for-each (lambda (tri)
            (match tri
              ((x y e)
               (deftestf 'round (e)
                 (el-expr `(let ((x ,x)
                                 (y ,y))
                             (print (round x y))))))))
          `((10 3 3)
            (10 -3 -3)
            (-10 3 -3)
            (-10 -3 3)
            (9.0001 3 3)
            (-11.9999 3 -4)
            (10 -3.3334 -3)))

(for-each (lambda (tri)
            (match tri
              ((x y e)
               (deftestf 'truncate (e)
                 (el-expr `(let ((x ,x)
                                 (y ,y))
                             (print (truncate x y))))))))
          `((10 3 3)
            (10 -3 -3)
            (-10 3 -3)
            (-10 -3 3)
            (9.0001 3 3)
            (-11.9999 3 -3)
            (10 -3.3334 -2)))
