(deftest ensure-empty-lines-arithmetic (ok)
  (el-expr `(let ((pass t))
    (set-buffer (get-buffer-create (generate-new-buffer-name "\" \"") nil))
    (insert "\" ‘ ’ “ ” \"")

    (goto-char (point-max))
    (when (not (equal 10 (point)))
      (setq pass nil)
      (message "\"  wrong point: %d\"" (point)))
    (when (not (equal 1 (point-min)))
      (setq pass nil)
      (message "\"  wrong point-min: %d\"" (point-min)))
    (when (not (equal 10 (point-max)))
      (setq pass nil)
      (message "\"  wrong point-max: %d\"" (point-max)))
    (when (not (equal 9 (buffer-size)))
      (setq pass nil)
      (message "\"  wrong buffer-size: %d\"" (buffer-size)))

    ;; Simulate the re-search-backward that ensure-empty-lines does
    (let ((found-pos (save-excursion
                       (if (re-search-backward "\"[^\\n]\"" nil t)
                           (+ (point) 2)
                         (point-min)))))
      (when (not (equal 11 found-pos))
        (setq pass nil)
        (message "\"  wrong found-pos (start): %d\"" found-pos))

      (when (not (equal 10 (point)))
        (setq pass nil)
        (message "\"  current point: %d\"" (point)))

      ;; Test the delete-region arithmetic from ensure-empty-lines
      (let* ((current-point (point))
             (start found-pos)
             (lines 1)
             (distance (- current-point start))
             (delete-start current-point)
             (delete-end (- current-point (- current-point start lines))))
        (when (not (equal -1 distance))
          (setq pass nil)
          (message "\"  wrong distance (point - start): %d - %d = %d\"" current-point start distance))
        (when (not (equal 10 delete-start))
          (setq pass nil)
          (message "\"  wrong delete-start: %d\"" delete-start))
        (when (not (equal 12 delete-end))
          (setq pass nil)
          (message "\"  wrong delete-end: %d - (%d - %d %d) = %d\"" current-point current-point start lines delete-end))))
    (if pass (print 'ok) (print 'fail)))))
