;;; test-m13-store.scm --- M13 imp-2 test corpus for
;;; (emacs kbd-buffer) kbd-buffer-store-event!
;;;
;;; Sourced by test/keyboard/test-m13-store.el via eval-scheme.
;;; Accumulates PASS/FAIL entries into `test-results` for readback
;;; from elisp — Scheme format output does not reach emacs --batch
;;; stdout.
;;;
;;; Covers the port of C kbd_buffer_store_buffered_event
;;; (src/keyboard.c:4601-4701): the already-holding guard, the ASCII
;;; keystroke modifier fold, the quit-char branch (hold-quit copy and
;;; the focus + handle_interrupt path), the stop-char branch, the ring
;;; append + last-slot silent drop, and the while-no-input quit-flag
;;; check (including the SELECTION_REQUEST_EVENT -> `selection-request'
;;; symbol trap).  The single_kboard reroute branch is not reachable in
;;; batch (one kboard only — see ertest-kboard.el:8); test 6 asserts at
;;; run time that the batch skip-condition holds rather than assuming
;;; which half is false.  Test 10 covers the review finding 1 NO_EVENT
;;; abort invariant (via a stubbed --kbd-abort).  Finding 2's quit-char
;;; kb nil-guard is added in the module but has no batch test: it is
;;; only observable through the single_kboard reroute condition, whose
;;; %--kbd-single-kboard-p / kboard-eq defelisp references are already
;;; delay-cached by earlier quit-char tests, so the guard cannot be
;;; exercised by stubbing in batch — deferred to imp-4 interactive smoke.
;;;
;;; kbd-buffer-store-event! is called directly as a Scheme procedure
;;; (it is exported but not elisp-visible yet, so %sym cannot reach it);
;;; %sym is used only for the C DEFUNs the corpus needs directly.  The
;;; kind constants are read from the module via @@ so the corpus uses
;;; the exact values kbd-buffer-store-event! compares against.  The
;;; --sys-suspend stop branch is stubbed (see "Do not" in brief.org) so
;;; the runner is never actually suspended.

(use-modules (emacs kbd-buffer)
             ((emacs event-modifiers) #:select (make-ctrl-char ctrl-modifier)))

(define test-results '())

(define (report name status)
  (set! test-results (cons (list name status) test-results)))

(define (check name expected actual)
  (if (equal? expected actual)
      (report name 'PASS)
      (report name (list 'FAIL 'expected expected 'got actual))))

(define (%sym name)
  (symbol-function name))

(define (truthy? x)
  (not (eq? x #nil)))

(define (elist . items)
  (let loop ((i items))
    (if (null? i) #nil (cons (car i) (loop (cdr i))))))

;; Kind constants — the authoritative values the module compares
;; against (KBD_BUFFER_SIZE is hardcoded here with a comment, same as
;; the module; no DEFUN exposes it).
(define ASCII-KEYSTROKE-EVENT   (@@ (emacs kbd-buffer) ASCII-KEYSTROKE-EVENT))
(define SELECTION-REQUEST-EVENT (@@ (emacs kbd-buffer) SELECTION-REQUEST-EVENT))
(define NO-EVENT                (@@ (emacs kbd-buffer) NO-EVENT))
(define KBD-BUFFER-SIZE 4096)

;;; --- 0. Registration: every store-side C DEFUN resolves --------------

;; Guards against a missing/renamed DEFUN silently reaching an
;; unreachable branch (e.g. the single_kboard reroute, which batch cannot
;; reach but imp-4's interactive smoke will).  set-kboard-kbd-queue is
;; macro-generated by KBOARD_LISP_FIELD ("kbd-queue", ...)
;; (src/keyboard.c:1592) — the DEFUN name never appears contiguously in
;; the C source, so resolve it at runtime rather than trusting grep.
(for-each
 (lambda (n)
   (check (string-append "registered:" (symbol->string n))
          #t (not (eq? (%sym n) #nil))))
 '(--ie-copy --kbd-set-store-ptr-index --kbd-maybe-hold-keyboard-input
   --set-kboard-kbd-queue-has-data --stop-character --sys-suspend
   --handle-interrupt-normal --quit-char --kbd-single-kboard-p
   kboard-eq set-kboard-kbd-queue --set-ie-frame-or-window --ie-kboard
   --ie-clear --set-ie-arg --get-internal-last-event-frame
   --set-internal-last-event-frame --frame-focus-frame --kbd-abort))

;;; --- 1. Plain ASCII keystroke: ring append ---------------------------

(let* ((ptr ((%sym '--kbd-store-ptr-index)))
       (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT 97 0 #nil)))
  (dynamic-wind
    (lambda () #f)
    (lambda ()
      (kbd-buffer-store-event! ie #f)
      (let ((stored ((%sym '--kbd-event-ie) ptr)))
        (check "store/ptr-advances-by-1"
               (modulo (+ ptr 1) KBD-BUFFER-SIZE)
               ((%sym '--kbd-store-ptr-index)))
        (check "store/kind" ASCII-KEYSTROKE-EVENT ((%sym '--ie-kind) stored))
        (check "store/code" 97 ((%sym '--ie-code) stored))
        (check "store/modifiers" 0 ((%sym '--ie-modifiers) stored))))
    (lambda () ((%sym '--kbd-set-store-ptr-index) ptr))))

;;; --- 2. Ctrl-modified keystroke: the fold reaches the quit path ------

;; C-g (103) with ctrl folds to quit_char: make-ctrl-char(103) == C-g ==
;; the C quit_char.  Precondition asserts the runtime's quit_char really
;; is 7 so the test is not silently vacuous.
(check "ctrl-fold/precondition-cg-is-quit" #t
       (= (make-ctrl-char 103) ((%sym '--quit-char))))
(let* ((ptr ((%sym '--kbd-store-ptr-index)))
       (hq ((%sym '--ie-test-hold-quit)))
       (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT 103 ctrl-modifier #nil)))
  (dynamic-wind
    (lambda () #f)
    (lambda ()
      (kbd-buffer-store-event! ie hq)
      ;; folded c == quit_char ⇒ quit-char branch: hold_quit copy, no
      ;; ring append.  This proves the ctrl fold ran (a bare 103 would
      ;; have ring-appended).
      (check "ctrl-fold/hold-quit-kind" ASCII-KEYSTROKE-EVENT
             ((%sym '--ie-kind) hq))
      (check "ctrl-fold/hold-quit-code" 103 ((%sym '--ie-code) hq))
      (check "ctrl-fold/hold-quit-modifiers" ctrl-modifier
             ((%sym '--ie-modifiers) hq))
      (check "ctrl-fold/ring-not-appended" ptr ((%sym '--kbd-store-ptr-index))))
    (lambda () ((%sym '--kbd-set-store-ptr-index) ptr))))

;;; --- 3. Already-holding guard ----------------------------------------

;; A hold-quit whose kind != NO_EVENT discards the event immediately.
(let* ((ptr ((%sym '--kbd-store-ptr-index)))
       (busy ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT 65 0 #nil))
       (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT 66 0 #nil)))
  ((%sym '--rks-vquit-flag-clear))
  (dynamic-wind
    (lambda () #f)
    (lambda ()
      (kbd-buffer-store-event! ie busy)
      (check "already-holding/ring-unmoved" ptr ((%sym '--kbd-store-ptr-index)))
      (check "already-holding/quit-flag-nil" #nil (symbol-value 'quit-flag)))
    (lambda () ((%sym '--kbd-set-store-ptr-index) ptr))))

;;; --- 4. Quit-char with hold-quit given -------------------------------

(let* ((ptr ((%sym '--kbd-store-ptr-index)))
       (hq ((%sym '--ie-test-hold-quit)))
       (qc ((%sym '--quit-char)))
       (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT qc 0 #nil)))
  (dynamic-wind
    (lambda () #f)
    (lambda ()
      (kbd-buffer-store-event! ie hq)
      (check "quit-hold/kind" ASCII-KEYSTROKE-EVENT ((%sym '--ie-kind) hq))
      (check "quit-hold/code" qc ((%sym '--ie-code) hq))
      (check "quit-hold/modifiers" 0 ((%sym '--ie-modifiers) hq))
      (check "quit-hold/ring-not-appended" ptr ((%sym '--kbd-store-ptr-index))))
    (lambda () ((%sym '--kbd-set-store-ptr-index) ptr))))

;;; --- 5. Quit-char, plain path (hold-quit = #f) -----------------------

;; Uses the selected frame as the event's frame_or_window so the
;; focus + handle_interrupt path has a real frame to record (a #nil
;; frame would store last-event-frame = #nil and the check would be
;; vacuous).
((%sym '--rks-vquit-flag-clear))
(let* ((frame ((%sym 'selected-frame)))
       (ptr ((%sym '--kbd-store-ptr-index)))
       (qc ((%sym '--quit-char)))
       (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT qc 0 frame)))
  (dynamic-wind
    (lambda () #f)
    (lambda ()
      (kbd-buffer-store-event! ie #f)
      (check "quit-plain/last-event-frame-set" #t
             (not (eq? (symbol-value 'last-event-frame) #nil)))
      (check "quit-plain/internal-last-event-frame-set" #t
             (not (eq? ((%sym '--get-internal-last-event-frame)) #nil)))
      (check "quit-plain/ring-not-appended" ptr ((%sym '--kbd-store-ptr-index))))
    (lambda () ((%sym '--kbd-set-store-ptr-index) ptr))))
((%sym '--rks-vquit-flag-clear))

;;; --- 6. Quit-char same-kboard: reroute skipped in batch --------------

;; Batch has a single kboard, so either single_kboard is false or kb ==
;; current_kboard.  Assert (not assume) that one half is false, so the
;; reroute branch is confirmed unreachable here (its real coverage is
;; imp-4's interactive smoke).  Tests 4 and 5 above already exercised a
;; non-reroute quit-char path.
(let* ((kb ((%sym 'current-kboard)))
       (single ((%sym '--kbd-single-kboard-p)))
       (same ((%sym 'kboard-eq) kb ((%sym 'current-kboard)))))
  (check "reroute/batch-skip-condition" #t
         (or (not (truthy? single)) (truthy? same))))

;;; --- 7. Stop-char match (stubbed sys_suspend) ------------------------

;; The stop branch calls a genuine sys_suspend () — never run for real
;; in batch (it would stop the runner).  Stub --sys-suspend's elisp
;; function slot to a recorder for the duration; kbd-buffer-store-event!
;; resolves the C DEFUN lazily via %--sys-suspend (first force here), so
;; the stub is what gets called.  Restore afterwards.  Gated on
;; stop-char != 0 (see the unreachable-report branch below).
(let* ((stop-char ((%sym '--stop-character)))
       (quit-char ((%sym '--quit-char)))
       (recorded #f)
       (saved-suspend (symbol-function '--sys-suspend)))
  (check "stop/precondition-distinct-from-quit" #t
         (not (= stop-char quit-char)))
  (if (not (= 0 stop-char))
      ;; stop-char nonzero: exercise the stop branch via a stubbed
      ;; sys_suspend.
      (dynamic-wind
        (lambda () (set-symbol-function! '--sys-suspend
                                         (lambda args (set! recorded args))))
        (lambda ()
          (let* ((ptr ((%sym '--kbd-store-ptr-index)))
                 (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT
                      stop-char 0 #nil)))
            (dynamic-wind
              (lambda () #f)
              (lambda () (kbd-buffer-store-event! ie #f))
              (lambda () ((%sym '--kbd-set-store-ptr-index) ptr)))
            (check "stop/dispatch-reached" #t (not (eq? recorded #f)))
            (check "stop/no-ring-append" ptr ((%sym '--kbd-store-ptr-index)))))
        (lambda () (set-symbol-function! '--sys-suspend saved-suspend)))
      ;; stop-char is 0 in this build (--stop-character's docstring: "do
      ;; not assume a value"); the C stop branch is `c && c ==
      ;; stop_character', so it is statically unreachable here.  Record
      ;; that fact instead of a vacuous pass; real coverage is imp-4
      ;; interactive smoke.
      (report "stop/unreachable-stop-char-zero" 'PASS)))

;;; --- 8. Ring-append refusal (last-slot silent drop) ------------------

;; Seed store-ptr to the slot just behind fetch-ptr: the append's
;; next_slot == fetch_ptr, so C discards the event (store-ptr unmoved).
(let* ((fetch ((%sym '--kbd-fetch-ptr-index)))
       (store-before ((%sym '--kbd-store-ptr-index)))
       (seed (modulo (- fetch 1) KBD-BUFFER-SIZE)))
  (dynamic-wind
    (lambda () #f)
    (lambda ()
      ((%sym '--kbd-set-store-ptr-index) seed)
      (let* ((ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT 65 0 #nil)))
        (kbd-buffer-store-event! ie #f))
      (check "ring-append/silent-drop" seed ((%sym '--kbd-store-ptr-index))))
    (lambda () ((%sym '--kbd-set-store-ptr-index) store-before))))

;;; --- 9. while-no-input quit-flag -------------------------------------

(let ((saved-toi (symbol-value 'throw-on-input))
      (saved-wni (symbol-value 'while-no-input-ignore-events)))
  (dynamic-wind
    (lambda () (set-symbol-value! 'throw-on-input 'TOI)
               (set-symbol-value! 'while-no-input-ignore-events #nil))
    (lambda ()
      ;; Non-ignored ASCII keystroke (code 65, neither quit nor stop)
      ;; qualifies as input → quit-flag is set.
      ((%sym '--rks-vquit-flag-clear))
      (let* ((ptr ((%sym '--kbd-store-ptr-index)))
             (ie ((%sym '--ie-test-event) ASCII-KEYSTROKE-EVENT 65 0 #nil)))
        (dynamic-wind
          (lambda () #f)
          (lambda () (kbd-buffer-store-event! ie #f))
          (lambda () ((%sym '--kbd-set-store-ptr-index) ptr)))
        (check "while-no-input/ascii-sets-quit-flag" 'TOI
               (symbol-value 'quit-flag)))
      ;; A SELECTION_REQUEST_EVENT is in the ignore table (is_ignored_event
      ;; maps it to `selection-request', no -event suffix — the symbol
      ;; trap this corpus guards against), so quit-flag must stay nil.
      ((%sym '--rks-vquit-flag-clear))
      (set-symbol-value! 'while-no-input-ignore-events
                         (elist 'selection-request))
      (let* ((ptr ((%sym '--kbd-store-ptr-index)))
             (ie ((%sym '--ie-test-event) SELECTION-REQUEST-EVENT 0 0 #nil)))
        (dynamic-wind
          (lambda () #f)
          (lambda () (kbd-buffer-store-event! ie #f))
          (lambda () ((%sym '--kbd-set-store-ptr-index) ptr)))
        (check "while-no-input/selection-ignored" #nil
               (symbol-value 'quit-flag))))
    (lambda () (set-symbol-value! 'throw-on-input saved-toi)
               (set-symbol-value! 'while-no-input-ignore-events saved-wni))))

;;; --- 10. NO_EVENT kind aborts (review finding 1) ---------------------

;; C aborts the whole process on a NO_EVENT kind (emacs_abort (),
;; keyboard.c:4604-4605).  Stub --kbd-abort to a recorder — same
;; lazy-force mechanism test 7 uses for --sys-suspend — so the abort
;; path is exercised without crashing the runner.  Only abort-invoked
;; is asserted: a stubbed abort returns, so the port then falls through
;; to ring-append! exactly as C would if emacs_abort returned (no
;; ring-unmoved claim is made).
(let* ((ptr ((%sym '--kbd-store-ptr-index)))
       (aborted #f)
       (saved-abort (symbol-function '--kbd-abort))
       (ie ((%sym '--ie-test-event) NO-EVENT 0 0 #nil)))
  (dynamic-wind
    (lambda () (set-symbol-function! '--kbd-abort
                                     (lambda args (set! aborted #t))))
    (lambda ()
      (kbd-buffer-store-event! ie #f)
      (check "no-event/abort-invoked" #t aborted))
    (lambda () (set-symbol-function! '--kbd-abort saved-abort)
               ((%sym '--kbd-set-store-ptr-index) ptr))))
